# Set Options
set -g default-terminal "screen-256color"
set -g terminal-overrides "xterm*:Tc"
set -g default-shell /usr/bin/zsh
set -g detach-on-destroy off
set -g mouse on

# Create and Switch Between Windows
bind -n M-t new-window -c "#{pane_current_path}"
bind -n M-q previous-window
bind -n M-e next-window
bind -n M-k killp

# Create and Swtich Between Sessions
bind -n M-T new-session -c "#{pane_current_path}"
bind -n M-Q switch-client -p
bind -n M-E switch-client -n
bind -n M-K kill-session

# Set To Rename to Current Path
set-option -g automatic-rename-format "#{b:pane_current_path}"
set-option -g automatic-rename on
set-option -g status-interval 1


# default statusbar color
set-option -g status-style "bg=#282828,fg=colour223" # bg=bg1, fg=fg1

# default window title colors
set-window-option -g window-status-style bg=colour214,fg=colour237 # bg=yellow, fg=bg1

# default window with an activity alert
set-window-option -g window-status-activity-style bg=colour237,fg=colour248 # bg=bg1, fg=fg3

# active window title colors
set-window-option -g window-status-current-style bg=red,fg=colour237 # fg=bg1

# pane border
set-option -g pane-active-border-style fg=colour250 #fg2
set-option -g pane-border-style fg=colour237 #bg1

# message infos
set-option -g message-style "bg=#282828,fg=#fbf1c7" # bg=bg2, fg=fg1

# writing commands inactive
set-option -g message-command-style "bg=#282828,fg=colour223" # bg=fg3, fg=bg1

# pane number display
set-option -g display-panes-active-colour colour250 #fg2
set-option -g display-panes-colour colour237 #bg1

# clock
set-window-option -g clock-mode-colour colour109 #blue

# bell
set-window-option -g window-status-bell-style bg=colour167,fg=colour235 # bg=red, fg=bg

## Theme settings mixed with colors (unfortunately, but there is no cleaner way)
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right-style none
set-option -g status-right-length "80"
set-window-option -g window-status-separator ""

set-option -g status-left "#[bg=#504945,fg=#fbf1c7] #S #[bg=#282828,fg=#504945,bold,noitalics,nounderscore]"
set-option -g status-right "#[bg=#282828,fg=#504945 bold, nounderscore, noitalics]#[bg=#504945,fg=#fbf1c7] %Y-%m-%d  %H:%M #[bg=colour239,fg=#a89984,bold,noitalics,nounderscore]#[bg=#a89984,fg=colour237] #h "

set-window-option -g window-status-current-format "#[bg=colour214,fg=#282828,bold,noitalics,nounderscore]#[bg=colour214,fg=colour239] #I #[bg=colour214,fg=colour239,bold] #W#{?window_zoomed_flag,*Z,} #[bg=#282828,fg=colour214,bold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[bg=#504945,fg=#282828,noitalics]#[bg=#504945,fg=#fbf1c7] #I #[bg=#504945,fg=#fbf1c7] #W #[bg=#282828,fg=#504945,noitalics]"

bind -n M-R source-file ~/.config/tmux/tmux.conf \; display " Config reloaded!"
