################
### MONITORS ###
################
monitor = HDMI-A-1, 1920x1080, 0x0, 1

#################
### AUTOSTART ###
#################
exec-once = sudo /opt/rocm/bin/rocm-smi --setperflevel low
exec-once = sudo xremap --watch ~/.config/xremap.yaml
exec-once = hyprctl setcursor macOS-White 24
exec-once = ~/.scripts/amdgpu.sh
exec-once = hyprpaper

#############################
### ENVIRONMENT VARIABLES ###
#############################
env = EDITOR, nvim
env = XCURSOR_SIZE, 24
env = HYPRCURSOR_SIZE, 24
env = XCURSOR_THEME, macOS-White
env = GTK_THEME, Gruvbox-Material-Dark

#####################
### LOOK AND FEEL ###
#####################
general {
  gaps_in = 5
  gaps_out = 10
  border_size = 2

  col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
  col.inactive_border = rgba(595959aa)

  resize_on_border = false
  allow_tearing = false
  layout = dwindle
}

decoration {
  rounding = 10
  active_opacity = 1.0
  inactive_opacity = 1.0

  shadow_range = 0
  drop_shadow = false
  shadow_render_power = 0

  col.shadow = rgba(1a1a1aee)

  blur{
    size = 8
    passes = 1
    enabled = true
    vibrancy = 0.1696
  }
}

animations {
  enabled = true
  bezier = myBezier, 0.05, 0.9, 0.1, 1.05
  animation = windows, 1, 7, myBezier
}

dwindle {
  pseudotile = true
  preserve_split = true
}

#############
### INPUT ###
#############
input {
  kb_layout = br
  follow_mouse = 1
  touchpad {
    natural_scroll = false
  }
}

###################
### KEYBINDINGS ###
###################
$MOD1 = SUPER
$MOD2 = SUPER SHIFT

bindm = $MOD1, mouse:272, movewindow
bindm = $MOD1, mouse:273, resizewindow

bind =      , PRINT, exec, hyprshot -m region --clipboard-only
bind = $MOD1, R, exec, rofi -show drun
bind = $MOD1, RETURN, exec, kitty
bind = $MOD1, J, togglesplit
bind = $MOD2, X, killactive

# Move focus
bind = $MOD1, w, movefocus, u
bind = $MOD1, a, movefocus, l
bind = $MOD1, s, movefocus, d
bind = $MOD1, d, movefocus, r

# Example special workspace
bind = $MOD1, apostrophe, togglespecialworkspace, magic
bind = $MOD2, apostrophe, movetoworkspace, special:magic

# Navigate between workspaces
bind = $MOD1, 1, workspace, 1
bind = $MOD1, 2, workspace, 2
bind = $MOD1, 3, workspace, 3
bind = $MOD1, 4, workspace, 4
bind = $MOD1, 5, workspace, 5
bind = $MOD1, 6, workspace, 6
bind = $MOD1, 7, workspace, 7
bind = $MOD1, 8, workspace, 8
bind = $MOD1, 9, workspace, 9
bind = $MOD1, Q, workspace, 10

# Move windows to specific workspaces
bind = $MOD2, 1, movetoworkspace, 1
bind = $MOD2, 2, movetoworkspace, 2
bind = $MOD2, 3, movetoworkspace, 3
bind = $MOD2, 4, movetoworkspace, 4
bind = $MOD2, 5, movetoworkspace, 5
bind = $MOD2, 6, movetoworkspace, 6
bind = $MOD2, 7, movetoworkspace, 7
bind = $MOD2, 8, movetoworkspace, 8
bind = $MOD2, 9, movetoworkspace, 9
bind = $MOD2, Q, movetoworkspace, 10

##############################
### WINDOWS AND WORKSPACES ###
##############################
windowrulev2 = nofocus,class:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrulev2 = workspace special:magic, class:vesktop
windowrulev2 = workspace special:magic, class:Spotify
windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = workspace 10,class:gamescope
windowrulev2 = fullscreen,class:gamescope
windowrulev2 = monitor 1,class:gamescope
