monitor= HDMI-A-1, 1920x1080, 0x0, 1

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = GTK_THEME, Gruvbox-Material-Dark:dark

exec-once = exec hyprpaper
exec-once = exec hyprctl setcursor MacOS-White 24
exec-once = exec sudo cpupower frequency-set -g performance
exec-once = exec sudo ~/.cargo/bin/xremap --watch ~/.config/xremap.yaml

general { 
    gaps_in = 5
    gaps_out = 20

    border_size = 2
    
    col.active_border = rgba(689d6aff) rgba(689d6aff) 45deg
    col.inactive_border = rgba(595959aa)
}

decoration {
    rounding = 10
    drop_shadow = false
}

dwindle {
    pseudotile = true 
    preserve_split = true
}

master {
    new_status = master
}

input {
    kb_layout = br
}

$MOD1 = SUPER
$MOD2 = SUPER SHIFT

bind =      , PRINT, exec, /usr/bin/hyprshot -m region --clipboard-only
bind = $MOD2, X, killactive,
bind = $MOD2, F, togglefloating,
bind = $MOD1, RETURN, exec, kitty
bind = $MOD1, R, exec, rofi -show drun

# Move focus with MOD1 + arrow keys
bind = $MOD1, left, movefocus, l
bind = $MOD1, right, movefocus, r
bind = $MOD1, up, movefocus, u
bind = $MOD1, down, movefocus, d

# Switch workspaces with MOD1 + [0-9]
bind = $MOD1, 1, workspace, 1
bind = $MOD1, 2, workspace, 2
bind = $MOD1, 3, workspace, 3
bind = $MOD1, 4, workspace, 4
bind = $MOD1, 5, workspace, 5
bind = $MOD1, 6, workspace, 6
bind = $MOD1, 7, workspace, 7
bind = $MOD1, 8, workspace, 8
bind = $MOD1, 9, workspace, 9
bind = $MOD1, Q, workspace, 10

# Move active window to a workspace with MOD1 + SHIFT + [0-9]
bind = $MOD2, 1, movetoworkspace, 1
bind = $MOD2, 2, movetoworkspace, 2
bind = $MOD2, 3, movetoworkspace, 3
bind = $MOD2, 4, movetoworkspace, 4
bind = $MOD2, 5, movetoworkspace, 5
bind = $MOD2, 6, movetoworkspace, 6
bind = $MOD2, 7, movetoworkspace, 7
bind = $MOD2, 8, movetoworkspace, 8
bind = $MOD2, 9, movetoworkspace, 9
bind = $MOD2, Q, movetoworkspace, 10

bind = $MOD1, apostrophe, togglespecialworkspace, magic
bind = $MOD2, apostrophe, movetoworkspace, special:magic

# Move/resize windows with MOD1 + LMB/RMB and dragging
bindm = $MOD1, mouse:272, movewindow
bindm = $MOD1, mouse:273, resizewindow

windowrulev2 = suppressevent maximize, class:.*

windowrulev2 = workspace 10,class:^steam_app_(.*)$
windowrulev2 = fullscreen,class:^steam_apps_(.*)$
windowrulev2 = monitor 1,class:^steam_apps_(.*)$

windowrulev2 = workspace special:magic, class:vesktop
windowrulev2 = suppressevent maximize, class:.*

windowrulev2 = workspace 10,class:gamescope
windowrulev2 = fullscreen,class:gamescope
windowrulev2 = monitor 1,class:gamescope
